#lang racket
(require rackunit)
(define (square x) (* x x))
(define (larger-square x y z) (if (>= x y)
                                  (if (>= x z)
                                      (+ (square x)
                                         (square y)
                                          )
                                      (+ (square x)
                                         (square z)
                                      ))
                                  (if (>= y z)
                                      (+ (square x)
                                         (square y)
                                         )
                                      (+ (square y)
                                         (square z)
                                      ))
                                  ))

(check-eq? (larger-square 3 4 2) 25)
(check-eq? (larger-square 3 3 3) 18)
(check-eq? (larger-square 6 3 2) 45)
(check-eq? (larger-square 2 4 5) 41)